routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('auth.login');
// });
route::get('/','catalogoController@index')->name('catalogo');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');









Route::get('/reg','adminController@register')->name('reg');
Route::get('/home', 'HomeController@index')->name('home');
Route::post('/registrarUsuario','adminController@registrarUsuario')->name('registrarUsuario');
//router para el catalogo
Route::get('/catalogo', 'catalogoController@index')->name('catalogo');
Route::get('/search_for_catalogo','catalogoController@search_for_catalogo')->name('productos.search_for_catalogo');
Route::post('/uploadavatar','adminController@uploadavatar');
Route::post('/uploadlogotipo','adminController@uploadlogotipo');


//para cofiguracion de otro negocio
Route::get("/nuevo",'config_system@index');
Route::post("/guardar_negocio",'config_system@save')->name("guardar_negocio");

Route::get("/alogin/{datos}","adminController@alogin")->name("alogin");


Route::middleware(['auth','verified'])->group(function () {


	Route::get('/configuracion', 'adminController@configuracion')->name('configuracion');
	Route::post('/updateuser', 'adminController@updateuser')->name('updateuser');

	///ruta para la vista de ruta---------------------
	Route::get("/rutas",'clientesController@rutas')->name('rutas');
	Route::post("/guardar_ruta","clientesController@guardar_ruta")->name('guardar_ruta');
	Route::post("/actualizar_ruta","clientesController@actualizar_ruta")->name('actualizar_ruta');
	Route::post("/see_ruta","clientesController@see_ruta")->name('see_ruta');
	Route::post("/edit_ruta","clientesController@edit_ruta")->name('edit_ruta');
	Route::post("/destroy_ruta","clientesController@destroy_ruta")->name('destroy_ruta');

	//------------------para pedidos--------------------------
	Route::post('/verPedido', 'pedidosController@verPedido')->name('verPedido');
	Route::get('/pedidos', 'pedidosController@index')->name('pedidos');
	Route::get('/paraPedidos', 'ventasController@paraPedidos')->name('paraPedidos');
	Route::post('/crearpedido', 'pedidosController@crearpedido')->name('crearpedido');
	Route::post("actualizar-pedido",'pedidosController@actualizar')->name('actualizar-pedido');
	Route::post("/verProdutosPedido",'pedidosController@verProPedido')->name("verProdutosPedido");

		//----------------ROUTER EN HISTORIAL-------------------------------------
		Route::get('/historial', 'historialController@index')->name('historial');
		Route::post('/Lista_vendidos', 'historialController@list_ajax')->name('Lista_vendidos');


		Route::resource('productos','ProductosController');
		Route::resource('ventas','ventasController');
		Route::resource('ofertas','ofertasController');
		Route::resource('clientes','clientesController');
		Route::resource('pedidoss','pedidosController');
		
		//ALTA A PROVEDORES-----------------
		Route::get('/storeProvedor','adminController@createProvedor')->name('storeProvedor');
		Route::get('/storeCategoria','adminController@createCategoria')->name('storeCategoria');
		Route::get('/storeLinea','adminController@createLinea')->name('storeLinea');
		Route::get('/storeMarca','adminController@createMarca')->name('storeMarca');
		Route::get('/storeProductos','ProductosController@store')->name('storeProducto');
		//--------------para agregar una nueva oferta
		Route::get('/crearOferta','ofertasController@createOferta')->name('crearOferta');

		Route::post('/uploadImg','adminController@uploadImg');
		Route::post('/uploadImgUser','adminController@uploadImgUser');
		
		Route::post('/buscarProducto','adminController@buscarProducto')->name('buscarProducto');
		Route::post('/actualizarExistencia',"ProductosController@updateExistencia")->name('actualizarExistencia');

		Route::post('/buscarXcodigo','adminController@buscarXcodigo')->name('buscarXcodigo');

		//-___________-rutas para exportar e importar_________________________-__
		Route::post('/productos-import-loadExcel','ProductosController@loadExcel')->name('productos.import.loadExcel');
		Route::get('/DescargarExcel', function () {
		    return Excel::download(new productoExport, 'productos_de_retail.xlsx');
		});
		//##################################################################################
		// Route::post('import-list-excel', 'UserController@importExcel')->name('users.import.excel');
		// Route::post('productos/delete','ProductosController@destroy')->name('deleteProductos');
		Route::get('productos-search','ProductosController@search')->name('productos.search');
		Route::get('clientes-search','clientesController@search')->name('clientes.search');
		
		Route::post('/verProducto','ProductosController@verProducto')->name('verProducto');
		Route::post("/vercliente",'clientesController@verCliente')->name('vercliente');

		Route::post("productos-actualizar",'ProductosController@actualizar')->name('actualizar');
		Route::post("actualizar-cliente",'clientesController@actualizar')->name('actualizar-cliente');
		Route::get('/clientes','clientesController@index')->name('clientes.index');

		//##############routes para ventas############################################
		Route::post("/venta",'ventasController@ventas');
		Route::post("/buscarClientes",'clientesController@buscarClientes')->name("buscarClientes");
});

resources/views/forms/modales.blade.php
@extends('layouts.app')
@section('content')

<!--window modal ######modal clientes################-->
  <div class="modal fullscreen-modal fade" id="modal_clientes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content" >
      	<div class="modal-header text-light" style="background-color: #28a745;" >
      		<h1><i class="fa fa-plus"></i> Cliente <i class="app-menu__icon fa fa-user"></i></h1>
      		<span id="imgParaPerfil"></span>
      	</div>
        <div class="modal-body">
        	<div id="div_alert2"></div>
        	<form action="{{route('clientes.store')}}" method="POST">
        		@csrf
        		<div class="row">

				    <div class="col">
						<label for="nombre">Nombre</label>
		        		<input type="text" name="nombre" class="form-control" placeholder="Nombre o nombres ">
		        		<label for="apellidos">Apellidos</label>
		        		<input type="text" name="apellidos" class="form-control" placeholder="apellidos">
						<label for="municipio">Municipio</label>
						<input type="text" name="municipio" class="form-control" placeholder="municipio o C.P.">
		        		<label for="localidad">Localidad</label>
		        		<input type="text" name="localidad" class="form-control" placeholder="Localidad">
						<label for="calle">Calle</label>
		        		<input type="text" name="calle" class="form-control" placeholder="Nombre y número">
				    </div>

				    <div class="col">

				      	<label for="telefono">teléfono</label>
		        		<input type="tel" name="telefono" class="form-control" >

		        		<label for="correo">Correo</label>
		        		<input type="email" name="correo" class="form-control">

						<label for="usuarioApp">Usuario Para la App</label>
		        		<input type="text" name="usuarioApp" class="form-control">

						<label for="password">Contraseña</label>
		        		<input type="password" name="password"  class="form-control">

		        		<label for="foto">Foto</label>
		        		<input type="text" name="foto" id="foto" class="form-control" readonly="" value="default.png">
				 </div>

			</div>
        		
		       	<br><br>
	        	<button type="submit" class="btn btn-success" style="float: right;">Guardar</button>
        	</form>

        	<form enctype="multipart/form-data" id="formsubirFoto" method="post">
        		<label for="imagen"><b>Subir foto:</b></label>
			  <input type="file" name="imagen" id="imagen" />
			  <button  type="submit" class="btn btn-primary" id="subirImg">subir</button>
        	</form>
		  


        </div>
      </div>
    </div>
  </div>











@endsection
@section('script')
<script type="text/javascript">

</script>
@endsection

resources/views/forms/ofertas.blade.php
@extends('layouts.app')
@section('content')
<div class="container" style="padding-left: 3px;padding-right: 3px">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card" >
            	<div class="card-header" style="background-color:#20c997">
            		<h6 class="text-light"><i class="fa fa-star text-warning fa-spin"></i> Agregar más ofertas</h6>
            	</div>
            	<div class="card-body">
            		@if(session('success'))
					<div class="alert alert-success alert-dismissible fade show">
						<h3>{{session('success')}}</h3>
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						    <span aria-hidden="true">&times;</span>
						</button>
					</div>
				@endif
				@if(session('error'))
					<div class="alert alert-danger alert-dismissible fade show">
						<h3>{{session('error')}}</h3>
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						    <span aria-hidden="true">&times;</span>
						</button>
					</div>
				@endif

            		<div class="row">
            			<div class="col-xl-3 col-md-6 mb-4 ">
            				<div class="form-inline d-flex justify-content-center md-form form-sm mt-0 input-group">
            					<input class="form-control " type="text" placeholder="Buscar"
							    aria-label="Search" id="input_search" autofocus="">
							    <button class="btn btn-primary" id="btn_buscar_prod"><i class="fa fa-search"></i></button>
            				</div>
							  
							
							<br>
							<form action="{{route('crearOferta')}}" method="get" id="form_oferta">
								<input type="number" name="id_producto" id="id" class="d-none" readonly="true">
							<label>Unidad</label>
							<input type="text" name="unidad" id="unidad" class="form-control" readonly="true">

	            			<label for="descripcion">Descripción del producto</label>
	            			<textarea class="form-control" name="descripcion_producto" id="descripcion" readonly="true"></textarea>
	            			
	            			<label>Precio de venta <b class="text-danger">$</b></label>
	            			<input type="number" name="precio_venta" id="precio_venta" class="form-control" readonly="true">

	            			<label >Precio de Oferta</label>
	            			<input type="number" name="precio_oferta" id="precio_oferta" class="form-control border-info">

	            			<label for="validez">Valido hasta</label>
	            			<input type="date" name="fecha_valido" id="validez" class="form-control border-info" >
	            			
	            			<label>Imagen</label>
	            			<input type="text" name="foto" id="foto" class="form-control" readonly="true">

	            			<label>Url de youtube</label>
	            			<input type="text" name="url" id="url" class="form-control border-info">
	            			<br>
	            			<a class="btn btn-success  text-light" id="btn_agregar" style="float: right;"><i class="fa fa-plus text-warning"></i> Agregar</a>
							</form>
							

            			</div>
            			<div class="col-xl-3 col-md-6 mb-4 contenedor" style="background:#EAECEE;text-align: center;height: 300px;padding-top: 45px" id="div_foto">
            				<img src="public/img/productos/no-images.jpg" class="imagen" style='margin-top:auto;margin-bottom:auto;width:80%'>
            			</div>
            			<style type="text/css">
							.contenedor:hover .imagen {-webkit-transform:scale(1.3);transform:scale(1.3);}
							.contenedor {overflow:hidden;}
            			</style>

            			<div class="col-xl-6 col-md-12 mb-4">
            				<hr>
            				<b class="badge badge-info" style="font-size: 130%">En oferta  </b> <span><i class="fa fa-shopping-bag text-success fa-2x"></i></b><h4 class="text-primary"></span>
            				<div class="table-responsive">
							  <table class="table table-striped table-bordered" id="tabla_oferta">
							    <thead class="table-dark">
							    	<tr>
							    		<th class="d-none">id</th>
							    		<th>id producto</th>
							    		<th>unidad</th>
							    		<th>Descripción</th>
							    		<th>Precio</th>
							    		<th>Precio de oferta</th>
							    		<th>fecha valido</th>
							    		<th><i class="fa fa-picture-o text-info"></i></th>
							    		<th><i class="fa fa-cog"></i></th>
							    		
							    	</tr>
							    </thead>
							    <tbody id="lista_ofertas">
							    	@foreach($ofertas as $oferta)
							    		<tr>
							    			<td class="d-none">{{$oferta->id}}</td>
							    			<td>{{$oferta->id_producto}}</td>
							    			<td>{{$oferta->unidad}}</td>
							    			<td>{{$oferta->descripcion_producto}}</td>
							    			<td>{{$oferta->precio_venta}}</td>
							    			<td>{{$oferta->precio_oferta}}</td>
							    			<td>{{$oferta->fecha_valido}}</td>
							    			<td><img src="public/img/productos/{{$oferta->foto}}" width="40px"></td>
							    			<td>
							    				
							    				<form action="{{ route('ofertas.destroy',$oferta->id) }}" method="post" class="btnAction">
							              			 @csrf
		                 							 @method('DELETE')
							              			<button class="btn btn-sm btn-danger" ><i class="fa fa-trash"></i></button>
							              		</form>
							    			</td>
							    		</tr>
							    	@endforeach
							    </tbody>
							  </table>
							</div>
            			</div>
            		</div>        		
           		</div>
        </div> 
            <!-- fin card -->
        </div>
        <style type="text/css">
        	#tabla_oferta thead tr th{
        		font-size: 60%;
        		padding: 2px;
        		border:1px;
        	}
        	#tabla_oferta tbody tr td{
        		font-size: 60%;
        		padding: 1px;
        		border:1px solid #eee;
        		border-bottom: 2px solid #66bb6a;

        	}
        </style>

    </div>
	</div>


<div class="modal" tabindex="-1" id="modal_buscar_prod" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color:#20c997">
        <h5 class="modal-title">Retail Stehs</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<p class="text-info">Pulse doble click para seleccionar el producto.</p>
      		<div class="table-responsive" style="overflow-y: scroll;height: 400px">
			  <table class="table table-striped" id="tab_modal_buscado">
			    <thead class="table-dark">
			    	<tr>
			    		<th>id</th>
			    		<th>Clave</th>
			    		<th>Unidad</th>
			    		<th>Descripción</th>
			    		<th>Precio</th>
			    		<th>Existencia</th>
			    		<th>Foto</th>
			    	</tr>
			    </thead>
			    <tbody id="lista_buscado">
			  	
			  </tbody>
			  </table>
			  <style type="text/css">
			  	#tab_modal_buscado thead tr th{
			  		padding:2px;
			  		padding-right: 3px;
			  		padding-left: 3px;
			  		border: 1px solid #eee;
			  	}
			  	#tab_modal_buscado tbody tr td{
			  		padding:0px;
			  		padding-right: 3px;
			  		padding-left: 3px;
			  		border: 1px solid #eee;
			  		border-bottom: 2px solid #aaa;
			  	}
			  </style>
			</div>
      </div>

    </div>
  </div>
</div>

<form id="form_get" class="d-none">
	@csrf
	<input type="" name="producto" value="" id="input_id_pro">
</form>





@endsection

@section('script')
<script type="text/javascript">
	$(".btn_toggle").trigger("click");
	if ($(window).width() <= 360) {
	    $(".btn_toggle").trigger("click");
	}

var eliminaroferta=function(id){
	alert("eliminando"+id);
}

//-------------------------------------------------------------------------------
	$("#btn_agregar").click(function(){
		var id_pro=$("#id").val();
		var cont=0;
		$("#lista_ofertas").find("tr td:first-child").each(function(){
			cont++;
			if ($(this).siblings("td").eq(0).html()==id_pro) {
				alert("YA ESTA AGREGADO");
			}else{
				$("#form_oferta").submit();
			}
		    });
		if (cont==0) {
			$("#form_oferta").submit();
		}
	});
//##############################################################################
	$("#btn_buscar_prod").click(function () {
		$("#input_id_pro").val($("#input_search").val());

		$("#modal_buscar_prod").modal("show");
		// alert($("#input_search").val());
		$("#lista_buscado").html('');
		$.ajax({
          url:'{{route("buscarProducto")}}',
          type:'POST',
          dataType:'json',
          data:$('#form_get').serialize()
            }
            ).done(function(e){
              if (e=="") {
               $("#lista_buscado").append("<tr class='text-danger'> <td  colspan='8'><b>No se encontró registro!!</b></td></tr>");
              }else{
                for(var x=0;x<e.length;x++){
                	if (e[x].fotos=='ninguno') {
                		$("#lista_buscado").append(
	                	"<tr tabindex='1' class='move'><td width='1px' >"
	                	+e[x].id+"</td><td>"
	                	+e[x].clave+"</td><td class=''>"
	                	+e[x].unidad+"</td><td>"
	                	+e[x].descripcion_articulo+"</td><td>"
	                	+e[x].precio_venta+"</td><td>"
	                	+e[x].existencia+"</td> <td class='d-non'><img src='public/img/productos/no-images.jpg' style='margin-top:auto;margin-bottom:auto;width:80%' class='imagen'></td></tr>"
	                	);
                	}else{
                		$("#lista_buscado").append(
	                	"<tr tabindex='1' class='move'><td width='1px' >"
	                	+e[x].id+"</td><td>"
	                	+e[x].clave+"</td><td class=''>"
	                	+e[x].unidad+"</td><td>"
	                	+e[x].descripcion_articulo+"</td><td>"
	                	+e[x].precio_venta+"</td><td>"
	                	+e[x].existencia+"</td> <td class='d-non'><img src='public/img/productos/"+e[x].fotos+"' style='margin-top:auto;margin-bottom:auto;width:80%' class='imagen'></td></tr>"
	                	);
                	}
                
               }//fin for
              }
              
              });//fin done 
	});
//_________________________________________________________________________________________________

	$("#lista_buscado").on("dblclick","tr",function(){
		// alert($(this).find("td").eq(0).html());
		$("#id").val($(this).find("td").eq(0).html());
		$("#unidad").val($(this).find("td").eq(2).html());
		$("#descripcion").val($(this).find("td").eq(3).html());
		$("#precio_venta").val($(this).find("td").eq(4).html());
		
		// alert($(this).find("td").eq(6).find("img").attr("src"));
		let fot=$(this).find("td").eq(6).find("img").attr("src");
		fot=fot.split("/");
		$("#foto").val(fot[3]);
		$("#div_foto").html($(this).find("td").eq(6).html());
		$("#modal_buscar_prod").modal("hide");
	});
//______________________________________________________________________________________________________
</script>
@endsection

resources/views/forms/pedidos.blade.php
@extends('layouts.app')
@section('content')
<div class="container" style="padding-left: -5px;padding-right: -5px;margin:0px;max-width: 100%;">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card" >
            	<div class="card-header" style="background-color:#9B59B6">
            		<h4 class="text-light"><i class="fa fa-book text-dark "></i> Pedidos 
            			<a class="btn btn-warning float-right" href="{{route('paraPedidos')}}"><i class="fa fa-plus"></i></a>
            			<a href="" class="btn btn-success float-right disabled">Pagos</a>
            			<a href="" class="btn btn-primary float-right disabled">Devoluciones</a>
            		</h4>
            	</div>
            	<div class="card-body">
         		<div id="contedido_historial">

         			<div class="table-responsive">
         				<h3 class="text-success"><i class="fa fa-list-alt"></i> Lista de pedidos</h3>

					  <table class="table table-striped table-bordered" id="table_pedidos" >
					    <thead class="table-dark" >
					    	<tr>
					    		<th>#</th>
					    		<th>cliente</th>
					    		<th>fechas</th>
					    		<!-- <th>fecha de enviado</th>
					    		<th>fecha de entregado</th> -->
					    		<!-- <th>ubicación de cliente</th> -->
					    		<th>ubicación de producto</th>
					    		<th>importe</th>
					    		<th>envio</th>
					    		<th>Subtotal</th>
					    		<th>descuento<i class="text-danger fas fa-money-check-alt"></i></th>
					    		<th>total</th>
					    		<th class="text-warning">status</th>
					    		<th><i class="fa fa-cog"></i></th>
					    	</tr>
					    </thead>
					    <tbody id="td_pedidos">
					    	@foreach($pedidos as $pedido)
					    	<tr>
					    		<td>{{$pedido->id}}</td>
					    		<td>{{$pedido->nombre}}</td>
					    		<td >
					    		<p data-toggle="tooltip" data-html="true" title="
					    		<em class='text-primary'>Pedido: </em><b>{{$pedido->fecha_pedido}}</b> 

					    		<em class='text-success'>Envio: </em><b>{{$pedido->fecha_enviado}}</b> 

					    		<em class='text-warning'>Recibido: </em><b>{{$pedido->fecha_recibido}}</b>">
					    				<b>Ver fechas</b>
					    			</p>
					    			
					    		</td>
					    		<td>{{$pedido->ubicacion_actual}}</td>
					    		<td>${{$pedido->importe}}</td>
					    		<td>${{$pedido->costo_envio}}</td>
					    		<td>${{$pedido->subtotal}}</td>
					    		<td class="text-danger">${{$pedido->descuento}}</td>
					    		<td class="text-primary">${{$pedido->total}}</td>
					    		<td class="text-white bg-warning">{{$pedido->status}}</td>
					    		<td>
					    			<button class="btn btn-sm btn-success" 
					              		onclick="$('#edit{{$pedido->id}}').submit();">
					              			<i class="fas fa-edit" style="font-size: 80%"></i>
					              	</button>
					              	@auth
          							@if(Auth::user()->type=="superadmin")
					              	<button class="btn btn-sm btn-danger" 
					              			onclick="$('#Form_eliminar_pedido{{$pedido->id}}').submit();">
					              			<i class="fa fa-trash" ></i>
					              		</button>

					              	<form action="{{ route('pedidoss.destroy',$pedido->id) }}" method="post" class="btnAction d-none" id="Form_eliminar_pedido{{$pedido->id}}">
						              @csrf
	                 				@method('DELETE')
						             <button class="btn btn-sm btn-danger" ><i class="fa fa-trash"></i></button>
						             </form>
						             @endif
						             @endauth
					              	<form action="{{route('verPedido') }}" method="post" class="btnAction d-none" id="edit{{$pedido->id}}">
					              			@csrf
                 						<input type="hidden" name="id" id="id_editar" value="{{$pedido->id}}">
					              		<button class="btn btn-sm btn-success">
					              		</button>
					              	</form>
					    		</td>
					    	</tr>
					    	@endforeach
					    	
					    </tbody>
					  </table>
					  {!!$pedidos->render() !!}
					  <style type="text/css">
					  	
					  	.fechas{margin: 0px;}
					  	#tab_listventa thead tr th{
					  		padding:2px;
					  		padding-right: 3px;
					  		padding-left: 3px;
					  		border: 1px solid #eee;
					  		}
					  		#tab_listventa tbody tr td{
					  		padding:0px;
					  		padding-right: 3px;
					  		padding-left: 3px;
					  		border: 1px solid #eee;
					  		border-bottom: 2px solid #aaa;
					  	}
					  </style>
					</div>

         		</div><!-- fin div contenido_historial -->

           		</div><!-- fn card -->
        </div> 
            <!-- fin card -->
        </div>
    </div>
	</div>


<div class="modal" tabindex="-1" id="modal_agregar_pedido" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header bg-info text-white">
        <h5 class="modal-title id_modal"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
  
   
      </div>

    </div>
  </div>
</div>





@endsection

@section('script')
<script type="text/javascript">
	$('[data-toggle="tooltip"]').tooltip();
	$(".btn_toggle").trigger("click");
	if ($(window).width() <= 360) {
	    $(".btn_toggle").trigger("click");
	}

</script>
@endsection

resources/views/forms/see_ruta.blade.php
@extends('layouts.app')
@section('content')
<div class="container" style="padding-left: 3px;padding-right: 3px">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card" >
            	<div class="card-header text-white" style="background:#28a745">
            		 <h4><i class="fas fa-route"></i> Rutas {{$ruta->nombre_ruta}}
            		 	<span class="float-right">ID {{$ruta->id}}</span>
            		 </h4>
            	</div>
            	<div class="card-body">
            		
            		
            		<div style="width: 100%" id="msj"></div>
            		
            <div id="map" style="width: 100%;height: 500px;background:#afecde">
			</div>

            	</div> <!-- fin body card -->
           	</div>
        </div> 
    </div>
</div>

@endsection

@section('script')

<script type="text/javascript" src="https://maps.google.com/maps/api/js?key=AIzaSyCjXtZCg-4A85t_1Nvxyp3ww0edOp7lqQ8"></script>

<script type="text/javascript" src="public/js/gmaps.js"></script>
<script type="text/javascript">
//$#################################################################
	if ($(window).width() <= 360) {
		    $(".btn_toggle").trigger("click");
		}
		$(".btn_toggle").trigger("click");
//################extrado datos de orgen y destino################
	<?php
		$origen=$ruta->origen;
		$origen=explode(",",$origen);
		$destino=$ruta->destino;
		$destino=explode(",", $destino);
	  ?>


//###################dibujando mapa#####################################
	dibuando_mapa();
	function dibuando_mapa(){
	var map;
	var latOrigin={{$origen[0]}};
	var lngOrigin={{$origen[1]}};
	var latDestino={{$destino[0]}};
	var lngDestino={{$destino[1]}};
      map = new GMaps({
        el: '#map',
        lat:latOrigin,
        lng:latOrigin
      });
      map.setCenter(latOrigin, lngOrigin);

      map.addMarker({ lat: latOrigin,
       lng: lngOrigin,
       title: 'SUCURSAL CENTRAL'
   });

	<?php 
		$latitud_seccion=$ruta->latitud_seccion;
		$latitud_seccion=explode("%", $latitud_seccion);
		$cantSeccion=count($latitud_seccion);

	
		for($x=1;$x<$cantSeccion;$x++){
			$Newposition=explode(",", $latitud_seccion[$x]);
			$nombre_secciones=explode("%",$ruta->nombre_secciones);
			$lastLat=0;$lastLng=0;
			if ($x>1) {
				$lastposition=explode(",", $latitud_seccion[$x-1]);
				$lastLat=$lastposition[0];
				$lastLng=$lastposition[1];
			}
		
		$newLat=$Newposition[0];
		$newLng=$Newposition[1];
		

		?>
		var newlat={{$newLat}};
		var newlng={{$newLng}};
		var lastlat={{$lastLat}};
		var lastlng={{$lastLng}};
		if ({{$x}}==1) {
			map.drawRoute({
          origin: [latOrigin, lngOrigin],  
          destination: [newlat,newlng],
          travelMode: 'driving',
          strokeColor: '#000000',
          strokeOpacity: 0.6,
          strokeWeight: 5
        });
       map.addMarker({
       	lat: newlat,
        lng: newlng,
        title:'{{$nombre_secciones[$x]}}'
       }); 
   }if({{$x}}>1){
   	map.drawRoute({
          origin: [lastlat,lastlng],  
          destination: [newlat,newlng],
          travelMode: 'driving',
          strokeColor: '#000000',
          strokeOpacity: 0.6,
          strokeWeight: 5
        });
       map.addMarker({
       	lat: newlat,
        lng: newlng,
       	title:'{{$nombre_secciones[$x]}}'
       }); 
   }//fin if script	
	<?php
	}//fin for de php	
?>
}//Fin function
    

</script>

@endsection